[project]
name = "cortex-core"
version = "0.1.0"
description = "Central orchestration engine for the Cortex Platform"
authors = [{ name = "Cortex Team" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiosqlite>=0.21.0",
    "asyncpg>=0.30.0",
    "cryptography>=44.0.0",
    "fastapi>=0.115.0",
    "pydantic>=2.10.0",
    "pydantic-settings>=2.8.0",
    "python-dotenv>=1.0.1",
    "python-jose>=3.4.0",
    "redis>=5.2.0",
    "sqlalchemy>=2.0.38",
    "uvicorn>=0.34.0",
]

[dependency-groups]
dev = [
    "alembic>=1.15.0",
    "mypy>=1.6.1",
    "pytest>=7.4.2",
    "pytest-asyncio>=0.21.1",
    "pytest-cov>=4.1.0",
    "ruff>=0.1.0",
    "types-python-jose>=3.4.0.20250224",
]

[tool.hatch.build.targets.wheel]
packages = ["app"]

[tool.uv]
package = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
