[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cortex_core"
version = "0.1.0"
description = "Cortex Core - An AI routing and conversation platform"
readme = "README.md"
authors = [{ name = "Cortex Team", email = "cortex@example.com" }]
license = { text = "MIT" }
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
]
dependencies = [
    "fastapi>=0.95.0",
    "uvicorn>=0.21.1",
    "pydantic>=2.0.0",
    "pydantic-settings>=2.0.0",
    "sqlalchemy>=2.0.0",
    "python-dotenv>=1.0.0",
    "python-jose[cryptography]>=3.3.0",
    "httpx>=0.24.0",
    "websockets>=11.0.0",
    "asyncio>=3.4.3",
    "msal>=1.22.0",
    "litellm>=0.1.1",
    "starlette>=0.28.0",
    "sse-starlette>=1.6.5",
    "fastmcp>=0.1.0",
]

[project.optional-dependencies]
dev = [
    "black>=23.3.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
    "pytest>=7.3.1",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.1.0",
    "mypy>=1.3.0",
]

[project.urls]
"Homepage" = "https://github.com/example/cortex-core"
"Bug Tracker" = "https://github.com/example/cortex-core/issues"

[tool.hatch.build.targets.wheel]
packages = ["cortex_core"]

[tool.black]
line-length = 88
target-version = ["py39"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "--cov=cortex_core --cov-report=term-missing"
testpaths = ["tests"]
asyncio_mode = "auto"
