[project]
name = "cortex-core"
version = "0.1.0"
description = "Central orchestration engine for the Cortex Platform"
authors = [{ name = "Cortex Team" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn>=0.23.2",
    "pydantic>=2.4.2",
    "pydantic-settings>=2.0.3",
    "sqlalchemy>=2.0.22",
    "alembic>=1.12.0",
    "asyncpg>=0.28.0",
    "aiosqlite>=0.19.0",
    "redis>=5.0.1",
    "python-jose>=3.3.0",
    "cryptography>=41.0.4",
    "python-multipart>=0.0.6",
    "passlib>=1.7.4",
    "python-dotenv>=1.0.0",
    "websockets>=12.0",
    "sse-starlette>=1.6.5",
]

[dependency-groups]
dev = [
    "black>=23.9.1",
    "isort>=5.12.0",
    "mypy>=1.6.1",
    "pytest>=7.4.2",
    "pytest-asyncio>=0.21.1",
    "httpx>=0.25.0",
    "pytest-cov>=4.1.0",
    "ruff>=0.1.0",
]

[tool.hatch.build.targets.wheel]
packages = ["app"]

[tool.uv]
package = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
